### ISSUE TITLE
how can i edit help options?

### ISSUE THREAD

**Issue by suneeshleone4** [galnir/Master-Bot#120]
I want to edit help options, but I am not able to find the help file

**Comment by galnir** [comment]
If you want to to change the language of the command take a look at [this](https://github.com/galnir/Master-Bot/issues/27), else you can disable it(read [this](https://github.com/galnir/Master-Bot/issues/81)) and then make your own help command.
The reason you're not able to find it is because the command comes with the Commando framework.

**Comment by suneeshleone4** [comment]
it's not possible to edit right?  so, I have to create a new help.js file?

**Comment by galnir** [comment]
Yeah, so as I said, disable the help command and then create a new one under the guild folder for example

**Comment by suneeshleone4** [comment]
Okey, Thank You for the bot. added your credits also.
