### ISSUE TITLE
Spotify link support

### ISSUE THREAD

**Issue by Princevikas** [galnir/Master-Bot#444]
**Explain your suggestion**
convert Spotify links to equivalent YouTube links , like groovy bot do it , i think there should be an API for converting these links YouTube equivalent links , not many self hosted bots do it , i think it be will be great feature to add , to stand out forward than the other self hosted bots🤔

**Comment by galnir** [comment]
Public bots(like the one you mentioned) are either bypassing YouTube's data API (for example by using Lavalink which I'm pretty sure they are using) or by paying YouTube for more API units(insert doubt). Spotify also impose a rate limit, meaning you can't call their API all day long.
Unless you asked YouTube for more, you have daily quota of 10k units. Now, each time you search a song by entering:
```!play songName```
you use 100 units. 10k/100 is 100, meaning if you search 100 songs you will run out of units to use for the day.
Playing a song using its url or passing a playlist url(no matter how big) costs 1 unit. 
This means in theory I can write a feature that will allow you to pass in a spotify url and it will play that song via YouTube(assuming it exists on YouTube). It's actually not 'in theory' because I already wrote a working prototype of that feature and came to a conclusion that it could only benefit a public bot, because **you don't host them yourself**.

My point is that there are many great features I could write, but my intention is to write great features **while also not making the bot harder to set up than it is now**. For example if integrating Lavalink wouldn't make the bot hard to set up, I would do it yesterday, because Lavalink removes the entire barrier of quota units.
I'm still looking into ways of replacing ytdl-core with Lavalink, I may be able to achieve both goals with docker
