### ISSUE TITLE
command !play

### ISSUE THREAD

**Issue by mrui0516** [galnir/Master-Bot#460]
**Explain your suggestion**
![image](https://user-images.githubusercontent.com/74146067/108872188-d40b2380-75f1-11eb-83d7-abd6b0c944ed.png)
 when i use !play to play a music bot doesnt give any sounds , and shows that erro ,and then the bot will Exit the channel automatically

**Comment by Bacon-Fixation** [comment]
are you using the en tire Master-Bot or did you alter the index.js ?

**Comment by mrui0516** [comment]
i just changed last line code ，changed to my own code

Bacon Fixation <notifications@github.com>于周二, 23/02/202116:34写道：

**Comment by Bacon-Fixation** [comment]
Really can't help you if you made modification, its in the Bug template my friend

**Comment by mrui0516** [comment]
i just changed to my own token

**Comment by mrui0516** [comment]
it has to change right?

**Comment by Bacon-Fixation** [comment]
ah i see, nah i wouldn't call that a modification

**Comment by Bacon-Fixation** [comment]
could you do me a favvor and fill out the template for a bug so we can have some more info to better help you 

Do not open an issue if you simply "copied" code over to your bot/another bot. This is absolutely not recommended and will cause bugs. Also do not open an issue if you modified code and added features and now it's not working right. This is because I can't figure it out and don't have the time to read your code and find out what you did wrong.

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Use 'x' command
2. provide 'y' argument

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu...]
 - Node Version(Should be v12 atleast): 
 - Are python 2.7 and Ffmpeg installed?:
 - How are you hosting the bot(Locally, on a vps, heroku, glitch...):

**Additional context**
Add any other context about the problem here.
