### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by QuantaNeon** [galnir/Master-Bot#702]
I have successfully dont everything to host the bot upto `npx prisma migrate dev` command
finally when i do node indes.ts

```
/home/ubuntu/music/src/index.ts:1
import { load } from '@lavaclient/spotify';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1032:15)
    at Module._compile (node:internal/modules/cjs/loader:1067:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47
```

I am on ubuntu 20.04 vps
node version is azul 17

**Comment by Bacon-Fixation** [comment]
pleaze fill out the bug template as it helps us with understanding the issue

### IMPORTANT : *DO NOT SKIP THIS STEPS AND DO NOT DELETE THEM. WE CAN NOT HELP YOU IF YOU DO NOT PROVIDE INFORMATION AND STEPS TO REPRODUCE*

Do not open an issue if you simply "copied" code over to your bot/another bot. This is absolutely not recommended and will cause bugs. Also do not open an issue if you modified code and added features and now it's not working right. This is because I can't figure it out and don't have the time to read your code and find out what you did wrong.

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Use 'x' command
2. provide 'y' argument

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu...]:
 - Node.js Version(Should be v16 at least): 
 - Is python 2.7 installed?:
 - How are you hosting the bot(Locally, on a vps, heroku, glitch...):

**Additional context**
Add any other context about the problem here.



you can try the following, 
[Lavalink](https://github.com/galnir/Master-Bot#lavalink-startup) make sure to run `npm install` then open a second terminal and run `java -jar LavaLink.jar` before `node /dis/index.js` in a separate terminal

Hope this Helps
Much Love
-Bacon

**Comment by QuantaNeon** [comment]
uh...what exactly do u want me to do?

**Comment by QuantaNeon** [comment]
IDK what happened...but it seems to be working fine now ;-;

**Comment by galnir** [comment]
> IDK what happened...but it seems to be working fine now ;-;

You can't run TS files, they need to be compiled into JS files. You run the bot using ```npm run dev``` (all it does it compile the files to TS and runs the compiled index file)
