### ISSUE TITLE
TypeError: Cannot read property 'hits' of undefined

### ISSUE THREAD

**Issue by SQ8891** [galnir/Master-Bot#84]
Hey! I get this error when i try to start the bot. 
The code i get error on is in lyrics.js on line 56

**Comment by galnir** [comment]
It seems like you haven't read the README(instructions). The first issue(cannot read module...) is solved by reading one of the first lines that says to install the dependencies(using ```npm i```). Besides that, you are getting an error when using the lyrics command because you didn't generate an api key or you didn't place the correct key in your config.json

Please read the instructions before opening issues in the future. I assume you are the one who opened #83 aswell

**Comment by Natemo6348** [comment]
Did you clone this repo and run npm i
