### ISSUE TITLE
Extra Playlist Functionality

### ISSUE THREAD

**Issue by Ncech99** [galnir/Master-Bot#86]
Maybe a feature where the admin user can set a playlist to be used on default when there is no song in the queue. I am unsure if it's even possible to just queue one song at a time from a playlist and keep doing that until a new song is requested to make it next in the queue.

**Comment by galnir** [comment]
It's possible to have a "24/7" command. I need to rewrite my playlist system so it will actually do what you say, queue one song at a time(process it one at a time so the api key won't get revoked because of too many requests).
A user can use the "24/7" command and to stop it use a "stop 24/7" or smt so the regular play command can be used.

**Comment by Ncech99** [comment]
That sounds good. I figure it would have to work differently separate from a regular playlist system to allow for regular requests to work.

**Comment by galnir** [comment]
Closing since this is already being worked on
