### ISSUE TITLE
Issue when trying to add new .js files

### ISSUE THREAD

**Issue by CaptainYannick** [galnir/Master-Bot#9]
Hi I have my own files I want to add to the bot but when I do & perform these commands nothing happens

**Comment by galnir** [comment]
Are you placing those files inside 1 of the 4 directories inside the commands folder?
If yes go here https://gist.github.com/ and paste one of those files

**Comment by CaptainYannick** [comment]
https://gist.github.com/CaptainYannick/37c0c6ac7fbe7aa82c547dbac13f8dcb

**Comment by galnir** [comment]
@CaptainYannick [Commando](https://discord.js.org/#/docs/commando/master/general/welcome) is a **framework** for discord.js. If you take a look at all my commands they have the same pattern, they start with the _class_ keyword and they have bunch of properties in the _constructor_.
Using Commando makes it easier and cleaner to write commands using discord.js, for example handling arguments before was a pain and now you handle them easily(e.g reddit command).
You're trying to write commands without all the functionality of Commando and that's why these commands are not working. 
Take a look at this [guide](https://discordjs.guide/commando/), it will help you understand Commando.
