### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by CheatcodeArlon** [galnir/Master-Bot#95]
TypeError: this.commands.filterArray is not a function

**Comment by galnir** [comment]
Please use the issue template..

**Comment by CheatcodeArlon** [comment]
wdym?

**Comment by galnir** [comment]
When you open an issue, you have a premade template to fill:

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Use 'x' command
2. provide 'y' argument

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu...]
 - Node Version(Should be v12 atleast): 
 - Are python 2.7 and Ffmpeg installed?:
 - How are you hosting the bot(Locally, on a vps, heroku, glitch...):

**Additional context**
Add any other context about the problem here.

**Comment by CheatcodeArlon** [comment]
Alright got it.

**Describe the bug**
I'm getting TypeError: this.commands.filterArray is not a function error

**To Reproduce**
This happens if I use any command.

**Expected behavior**
Maybe something wrong with discordjs-commando. I mean I got an error while installing them.

**Screenshots**
[image](https://user-images.githubusercontent.com/62479310/84175347-7784ca00-aa9d-11ea-9f13-4df67f3c5430.png)

**Desktop** :

- OS: Windows 
- Node Version: 12.18.0
- Are python 2.7 and Ffmpeg installed?: Yes.
- How are you hosting the bot: Locally.

**Comment by galnir** [comment]
That is a problem with discord.js-commando. Did you clone this repo? If yes just ```npm install```

**Comment by CheatcodeArlon** [comment]
Alright thanks man its fixed now
